[project]
name = "ant_colony_optimization"
version = "0.1.0"
description = "A Python package implementing the Ant Colony Optimization algorithm."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numba>=0.61.2",
    "numpy>=2.2.6",
]
